apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.apigee.googleapis.com
spec:
  group: apigee.googleapis.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              apiProducts:
                type: array
                items:
                  type: string
              keyExpiresIn:
                type: number
              developerEmail:
                type: string
              scopes:
                type: array
                items:
                  type: string
              callbackUrl:
                type: string
              accessType:
                type: string
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
  scope: Namespaced
  names:
    plural: apps
    singular: app
    kind: App
    shortNames:
    - app
