apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: developers.apigee.googleapis.com
spec:
  group: apigee.googleapis.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              email:
                type: string
              firstName:
                type: boolean
              lastName:
                type: string
              userName:
                type: boolean
              status:
                type: string
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
  scope: Namespaced
  names:
    plural: developers
    singular: developer
    kind: Developer
    shortNames:
    - developer
