# Chart.yaml
apiVersion: v2
name: apigee-developer-crd
version: 0.1.0
appVersion: "1.0" # This refers to the version of the application (your CRD)
description: A Helm chart for the ApigeeDeveloper Custom Resource Definition.
type: application
keywords:
  - apigee
  - crd
  - developer
home: https://github.com/AyoSal/argocd-apimops # Replace with your repo if desired
sources:
  - https://github.com/AyoSal/argocd-apimops/tree/main/manifests/developer-crd # Example source
maintainers:
  - name: AyoS
  
